services:
  nats:
    image: docker.io/nats:latest
    ports:
    - "4222:4222"
    - "8222:8222"
    command: 
    - "--js"
  mongodb:
      image: docker.io/mongo:latest
      ports:
        - "27017:27017"
  publisher:
    build: .
    command: 
      - "/hello-http"
      - "publisher"
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "8080:8080"
    depends_on:
      - nats
  consumer:
    build: .
    command: 
      - "/hello-http"
      - "consumer"
    environment:
      - NATS_URL=nats://nats:4222
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - nats
      - mongodb
